# Generated by Django 2.0.9 on 2018-11-19 16:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Don`t change!', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sender', models.EmailField(blank=True, max_length=255, null=True)),
                ('sender_field', models.CharField(blank=True, max_length=128, null=True)),
                ('email_subject', models.CharField(default='New Web Submission', max_length=255)),
                ('email_text', wagtail.core.fields.RichTextField(blank=True, default='\n<p>Hello <strong>{{ user }}</strong>,</p>\n<p>Someone has submitted the contact form at <strong>{{ host }}</strong>:<br />\nThe request was submitted on <strong>{{ created|date }}</strong> at <strong>{{ created|time }}</strong>\nfrom the IP address of <strong>{{ ip }}</strong>.</p>\n<p>Request details:</p>\n<p>{{ data }}</p>\n<p>Truly yours,<br />\nMailer daemon @ <strong>{{ host }}</strong></p>', verbose_name='body')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=128, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='tmp')),
                ('file2', models.FileField(blank=True, max_length=255, null=True, upload_to='tmp')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Form')),
            ],
            options={
                'verbose_name_plural': 'Histories',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='contact.Form')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCompleteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('export', models.BooleanField(default=False)),
            ],
        ),
    ]
