# Generated by Django 2.0.9 on 2018-12-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_form_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='source',
        ),
        migrations.AddField(
            model_name='history',
            name='source',
            field=models.CharField(choices=[('default', '110090'), ('seo', '110091'), ('ppc', '110092')], default='default', max_length=20),
        ),
    ]
