# Generated by Django 2.0.9 on 2018-12-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20181214_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='source',
        ),
        migrations.AddField(
            model_name='history',
            name='seed',
            field=models.CharField(choices=[('110090', '110090'), ('110091', '110091'), ('110092', '110092')], default='110090', max_length=20, verbose_name='Spam Protection Seed'),
        ),
    ]
