# Generated by Django 2.0.9 on 2022-10-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20181218_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='sent',
            field=models.BooleanField(default=True),
        ),
    ]
