# Generated by Django 2.0.9 on 2018-11-19 14:23

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.fields.StreamField([('grid_container', wagtail.blocks.StructBlock([('grid_padding', wagtail.blocks.ChoiceBlock(choices=[('', 'No padding'), ('grid-padding-x', 'Padding X'), ('grid-margin-x', 'Margin X')], required=False)), ('grid_align', wagtail.blocks.ChoiceBlock(choices=[('', 'No align'), ('align-justify', 'Justify'), ('align-middle align-justify', 'Middle Justify')], required=False)), ('additional_classes', wagtail.blocks.CharBlock(required=False)), ('inner_additional_classes', wagtail.blocks.CharBlock(required=False)), ('body', wagtail.blocks.StreamBlock([('full_width_content_section', wagtail.blocks.StructBlock([('body', wagtail.blocks.StructBlock([('additional_classes', wagtail.blocks.CharBlock(required=False)), ('body', wagtail.blocks.StreamBlock([('text_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock()), ('mobile_hidden_text', home.blocks.SpoilerMobileText())]))])), ('content_image_slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))])), ('bordered_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('grouped_image', wagtail.blocks.StructBlock([('first_image', wagtail.images.blocks.ImageChooserBlock()), ('second_image', wagtail.images.blocks.ImageChooserBlock())])), ('square_content_image_slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))])), ('benefits_block', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.RichTextBlock())]))]))]))])), ('content_section', wagtail.blocks.StructBlock([('left_part', wagtail.blocks.StructBlock([('additional_classes', wagtail.blocks.CharBlock(required=False)), ('body', wagtail.blocks.StreamBlock([('text_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock()), ('mobile_hidden_text', home.blocks.SpoilerMobileText())]))])), ('content_image_slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))])), ('bordered_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('grouped_image', wagtail.blocks.StructBlock([('first_image', wagtail.images.blocks.ImageChooserBlock()), ('second_image', wagtail.images.blocks.ImageChooserBlock())])), ('square_content_image_slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))])), ('benefits_block', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.RichTextBlock())]))]))])), ('right_part', wagtail.blocks.StructBlock([('additional_classes', wagtail.blocks.CharBlock(required=False)), ('body', wagtail.blocks.StreamBlock([('text_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock()), ('mobile_hidden_text', home.blocks.SpoilerMobileText())]))])), ('content_image_slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))])), ('bordered_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('grouped_image', wagtail.blocks.StructBlock([('first_image', wagtail.images.blocks.ImageChooserBlock()), ('second_image', wagtail.images.blocks.ImageChooserBlock())])), ('square_content_image_slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))])), ('benefits_block', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.RichTextBlock())]))]))]))])), ('faq_section', wagtail.blocks.StructBlock([('questions', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock()), ('answer', wagtail.blocks.RichTextBlock())])))]))]))]))])),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='OfficePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('address', models.TextField()),
                ('footer_more_details', models.TextField(blank=True)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('working_hours', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Office image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Office Page',
                'verbose_name_plural': 'Office Pages',
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]
