# Generated by Django 2.0.9 on 2018-12-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20181204_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='officepage',
            name='location_coordinates',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
