# Generated by Django 2.1.3 on 2018-11-12 13:16

from django.db import migrations
import home.blocks
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181112_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('index_slider', wagtail.core.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('first_line', wagtail.core.blocks.CharBlock()), ('second_line', wagtail.core.blocks.CharBlock()), ('third_line', wagtail.core.blocks.CharBlock()), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True))), ('cta_text', wagtail.core.blocks.CharBlock())])), ('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', home.models.CustomRichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('content_section', wagtail.core.blocks.StructBlock([('left_part', wagtail.core.blocks.StreamBlock([('text_block', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(required=False)), ('content', wagtail.core.blocks.StreamBlock([('rich_text', wagtail.core.blocks.RichTextBlock()), ('mobile_hidden_text', home.blocks.SpoilerMobileText())]))])), ('double_image_block', wagtail.core.blocks.StructBlock([('first_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('second_image', wagtail.images.blocks.ImageChooserBlock(required=True))]))]))]))]),
        ),
    ]
