# Generated by Django 2.1.3 on 2018-11-12 15:05

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import home.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmetadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0011_auto_20181112_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title')), ('paragraph', home.models.CustomRichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('content_section', wagtail.blocks.StructBlock([('background', wagtail.images.blocks.ImageChooserBlock(required=False)), ('left_part', wagtail.blocks.StreamBlock([('text_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock()), ('mobile_hidden_text', home.blocks.SpoilerMobileText())]))])), ('double_image_block', wagtail.blocks.StructBlock([('first_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('second_image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('content_image_slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))]))])), ('right_part', wagtail.blocks.StreamBlock([('text_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock()), ('mobile_hidden_text', home.blocks.SpoilerMobileText())]))])), ('double_image_block', wagtail.blocks.StructBlock([('first_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('second_image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('content_image_slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))]))]))])), ('simple_gallery', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))])), ('simple_page_header', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(required=True)), ('cta_text', wagtail.blocks.CharBlock(default='Book an appointment', required=True))])), ('services_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(required=False))]))])),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Service Page',
                'verbose_name_plural': 'Service Pages',
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('index_slider', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('first_line', wagtail.blocks.CharBlock()), ('second_line', wagtail.blocks.CharBlock()), ('third_line', wagtail.blocks.CharBlock()), ('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True))), ('cta_text', wagtail.blocks.CharBlock())])), ('heading', wagtail.blocks.CharBlock(classname='full title')), ('paragraph', home.models.CustomRichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('content_section', wagtail.blocks.StructBlock([('background', wagtail.images.blocks.ImageChooserBlock(required=False)), ('left_part', wagtail.blocks.StreamBlock([('text_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock()), ('mobile_hidden_text', home.blocks.SpoilerMobileText())]))])), ('double_image_block', wagtail.blocks.StructBlock([('first_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('second_image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('content_image_slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))]))])), ('right_part', wagtail.blocks.StreamBlock([('text_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock()), ('mobile_hidden_text', home.blocks.SpoilerMobileText())]))])), ('double_image_block', wagtail.blocks.StructBlock([('first_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('second_image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('content_image_slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))]))]))])), ('simple_gallery', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))])), ('simple_page_header', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(required=True)), ('cta_text', wagtail.blocks.CharBlock(default='Book an appointment', required=True))])), ('services_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(required=False))]))]),
        ),
    ]
