# Generated by Django 2.1.3 on 2018-11-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181112_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='menu_icon',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second')], default='', help_text='Icon for service menus', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepage',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short descriptions for service menus'),
        ),
    ]
