# Generated by Django 2.1.3 on 2018-11-12 18:31

from django.db import migrations
import home.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20181112_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='body',
            field=wagtail.fields.StreamField([('team_member_block', wagtail.blocks.StructBlock([('background', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.blocks.CharBlock(required=True)), ('name', wagtail.blocks.CharBlock(required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('job_title', wagtail.blocks.CharBlock(required=True)), ('content', wagtail.blocks.RichTextBlock())])), ('cta_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(default='Let Us Bring Your Vision to Life!', required=True)), ('form_cta_text', wagtail.blocks.CharBlock(default='Book a free consultation', required=True)), ('phone_cta_text', wagtail.blocks.CharBlock(default='Speak with an artist:', required=True)), ('phone_cta_number', wagtail.blocks.CharBlock(required=True))])), ('instagram_block', home.blocks.InstagramBlock()), ('testimonials_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=True)), ('testimonials', wagtail.blocks.ListBlock(home.blocks.TestimonialBlock))])), ('large_gallery_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))]))]),
        ),
    ]
